### ISSUE TITLE
Styling improvements in navbar and pop-up menu

### ISSUE THREAD

**Issue by AdarshNaidu** [ACM-NITK/ACM-Website#7]
These improvements can be done according to me:- 
 

1. `1px solid black border` on the pop-up menu (_looked well when I tried on inspect mode_)
2. Pop-up menu can be centered with respect to YANTRAS navbar menu item
3. Center the text of menu items (_keep only if it looks good_)
4. Any further enhancements if it's makes it look good.

**Comment by hmd0404-nitk-eee** [comment]
I have worked out about it and got these two outputs. Which of the two is better and if not what could be improved further?
![#7_1](https://user-images.githubusercontent.com/55345366/70899178-1ca57500-201c-11ea-908a-88424259d782.png)
![#7_2](https://user-images.githubusercontent.com/55345366/70899180-1d3e0b80-201c-11ea-887c-a3262112fb4c.png)
